# Exercícios Numpy

####  Multiplicação

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

vetor_multiplicado = 2 * a

print(vetor_multiplicado)

[2 4 6 8]


#### Divisão
**Exercício:**
Sabendo que a operação de divisão é feita por __/__ , divida o vetor *a* por 2.

In [3]:
vetor_dividido = a / 2
print(vetor_dividido)

[0.5 1.  1.5 2. ]


#### Potência
**Exercício:**
Sabendo que a operação de potenciação é feita por __**__ , calcule o quadrado dos elementos do vetor *a*.

In [4]:
vetor_elevado = a**2
print(vetor_elevado)

[ 1  4  9 16]


#### Incrementar +=

In [5]:
print(a)

a += a

print(a)

[1 2 3 4]
[2 4 6 8]


### Exercício: encontre a média e o desvio padrão da matriz, sabendo que os métodos são representados por `np.mean()` e `np.std()`, respectivamente.

In [6]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
# média dos valores de stats
media = np.mean(stats)
print(media)

3.5


In [8]:
# desvio padrão dos valores de stats
dvpad = np.std(stats)
print(dvpad)


1.707825127659933


In [9]:
# linha

soma_colunas = np.sum(stats, axis=1)
print(soma_colunas)


[ 6 15]


### Realize a soma para cada linha e para cada coluna:

In [10]:
# coluna

soma_linhas = np.sum(stats, axis=0)
print(soma_linhas)

[5 7 9]


#### Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [11]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[1 2 3 4 5 6 7 8 9]


2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [12]:
pares = np.where((array%2)!=0, 0, array)
print(pares)

[0 2 0 4 0 6 0 8 0]


3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [13]:
filedata = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',',  usecols=[0,1,2,3])
print (filedata[0:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [14]:
sepallenght_data = filedata[:,0]

# print (sepallenght_data)

sepallenght_mean = np.mean(sepallenght_data)
sepallenght_median = np.median(sepallenght_data)
sepallenght_std = np.std(sepallenght_data)

print(sepallenght_mean, sepallenght_median, sepallenght_std)


5.843333333333334 5.8 0.8253012917851409


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [15]:
filtro = (filedata[:,2]>1.5) & (filedata[:,0]<5)

print(filedata[filtro])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


6 - Esse dataset possui nans?

In [16]:
numero_nans = np.sum(np.isnan(filedata))
print(f"Número de NAN = {numero_nans}")

Número de NAN = 0


7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [17]:
volume = (np.pi/3) * filedata[:,2]  * (filedata[:,0]**2)



nova_tabela = np.hstack((filedata, np.transpose([volume])))

with np.printoptions(precision=2):
    print(nova_tabela)

[[5.10e+00 3.50e+00 1.40e+00 2.00e-01 3.81e+01]
 [4.90e+00 3.00e+00 1.40e+00 2.00e-01 3.52e+01]
 [4.70e+00 3.20e+00 1.30e+00 2.00e-01 3.01e+01]
 [4.60e+00 3.10e+00 1.50e+00 2.00e-01 3.32e+01]
 [5.00e+00 3.60e+00 1.40e+00 2.00e-01 3.67e+01]
 [5.40e+00 3.90e+00 1.70e+00 4.00e-01 5.19e+01]
 [4.60e+00 3.40e+00 1.40e+00 3.00e-01 3.10e+01]
 [5.00e+00 3.40e+00 1.50e+00 2.00e-01 3.93e+01]
 [4.40e+00 2.90e+00 1.40e+00 2.00e-01 2.84e+01]
 [4.90e+00 3.10e+00 1.50e+00 1.00e-01 3.77e+01]
 [5.40e+00 3.70e+00 1.50e+00 2.00e-01 4.58e+01]
 [4.80e+00 3.40e+00 1.60e+00 2.00e-01 3.86e+01]
 [4.80e+00 3.00e+00 1.40e+00 1.00e-01 3.38e+01]
 [4.30e+00 3.00e+00 1.10e+00 1.00e-01 2.13e+01]
 [5.80e+00 4.00e+00 1.20e+00 2.00e-01 4.23e+01]
 [5.70e+00 4.40e+00 1.50e+00 4.00e-01 5.10e+01]
 [5.40e+00 3.90e+00 1.30e+00 4.00e-01 3.97e+01]
 [5.10e+00 3.50e+00 1.40e+00 3.00e-01 3.81e+01]
 [5.70e+00 3.80e+00 1.70e+00 3.00e-01 5.78e+01]
 [5.10e+00 3.80e+00 1.50e+00 3.00e-01 4.09e+01]
 [5.40e+00 3.40e+00 1.70e+00 2.00e-01 5.